"""added users table

Revision ID: 2593f9dea1a4
Revises: f0ad0f5af8cc
Create Date: 2023-10-02 22:14:02.770811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2593f9dea1a4'
down_revision = 'f0ad0f5af8cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=255), nullable=True))
        batch_op.drop_column('super_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('super_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
