"""add quanity to  transaction table

Revision ID: 36640c64327c
Revises: 3288b8d725fd
Create Date: 2023-10-03 21:50:16.004175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36640c64327c'
down_revision = '3288b8d725fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.drop_column('pieces')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pieces', sa.INTEGER(), nullable=True))
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
