"""added username unique constraint

Revision ID: 724d0b92f6b4
Revises: 2593f9dea1a4
Create Date: 2023-10-02 23:32:07.813401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724d0b92f6b4'
down_revision = '2593f9dea1a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))
        batch_op.create_unique_constraint('user_unique_constraint', ['username'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('user_unique_constraint', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
