"""Create Cart, Cart Items, Transcation

Revision ID: ce25702d178c
Revises: 36640c64327c
Create Date: 2023-10-04 13:40:40.246895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce25702d178c'
down_revision = '36640c64327c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_carts_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], name=op.f('fk_cart_items_cart_id_carts')),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], name=op.f('fk_cart_items_photo_id_photos')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_item_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('purchased_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_constraint('fk_transactions_photo_id_photos', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_transactions_cart_item_id_cart_items'), 'cart_items', ['cart_item_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('amount')
        batch_op.drop_column('quantity')
        batch_op.drop_column('photo_id')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('photo_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_transactions_cart_item_id_cart_items'), type_='foreignkey')
        batch_op.create_foreign_key('fk_transactions_photo_id_photos', 'photos', ['photo_id'], ['id'])
        batch_op.drop_column('purchased_at')
        batch_op.drop_column('cart_item_id')

    op.drop_table('cart_items')
    op.drop_table('carts')
    # ### end Alembic commands ###
