"""Add photo_id column to transactions

Revision ID: fa2f8da1ac21
Revises: ce25702d178c
Create Date: 2023-10-04 14:04:02.641954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2f8da1ac21'
down_revision = 'ce25702d178c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_transactions_photo_id_photos'), 'photos', ['photo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transactions_photo_id_photos'), type_='foreignkey')
        batch_op.drop_column('photo_id')

    # ### end Alembic commands ###
